site_name: PostProcessing
repo_url: https://github.com/./PostProcessing
site_url: https://..github.io/PostProcessing
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: TataiQ
edit_uri: edit/main/docs/
repo_name: ./PostProcessing
copyright: Maintained by <a href="https://..com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/./PostProcessing
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/PostProcessing

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true