---
apis:
  camera_group: "http://10.0.153.141:8000/getCameraGroup"
  preprocess_config: "http://10.0.153.141:8000/getCameraGroup"
  schedule_config: "http://10.0.153.141:8000/getCameraConfig"
  postprocess_config: "http://10.0.153.141:8000/getpostprocess"
  usecase_urls: "http://10.0.153.141:8000/getusecase"
  classes: "http://10.0.153.141:8000/getclasses"
  computation: "http://10.0.153.141:8000/getcomputation"
  incidents: "http://10.0.153.141:8000/getincidents"
  boundary_config: "http://10.0.153.141:8000/getboundary"
  

kafka:
  - 172.31.26.109:9092

tracking_server:
  host: "10.0.153.141"
  port: "50051"


