# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from grpc_protos import trackgrpc_pb2 as trackgrpc__pb2


class trackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.gettrack = channel.unary_unary(
            "/trackgrpcpkg.track/gettrack",
            request_serializer=trackgrpc__pb2.TrackRequest.SerializeToString,
            response_deserializer=trackgrpc__pb2.TrackResponse.FromString,
        )


class trackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def gettrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_trackServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "gettrack": grpc.unary_unary_rpc_method_handler(
            servicer.gettrack,
            request_deserializer=trackgrpc__pb2.TrackRequest.FromString,
            response_serializer=trackgrpc__pb2.TrackResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("trackgrpcpkg.track", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class track(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def gettrack(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/trackgrpcpkg.track/gettrack",
            trackgrpc__pb2.TrackRequest.SerializeToString,
            trackgrpc__pb2.TrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
